< config.mk

results/%.converted.vcf.gz:Q:	results/%.converted.vcf
	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS sort 
#	bgzip -c $prereq > $target.build \
#	&& tabix -p vcf $target.build \
#	&& mv $target.build $target \
#	&& mv $target.build.tbi $target.tbi #\
#	&& rm $prereq

results/%.converted.vcf: results/%.tmp.header results/%.tmp.body
	set -x
	mkdir -p `dirname $target`
#	cat $prereq > $target.build \
#	&& mv $target.build $target \
#	&& rm $prereq

results/%.tmp.header: results/%.converted.raw
	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS view -h $prereq > $target.build \
#	&& mv $target.build $target

##Remove variants with "N" as reference allele; replace MT for "M"; and replace line start (^) with "chr";
results/%.tmp.body: results/%.converted.raw
	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS view -H $prereq \
#	| awk ' BEGIN { FS="\t"; OFS="\t"; }
#		$4 !~ /N/ {
#			if ( $1 == "MT" ) $1="M";
#			print "chr"$0
#			} ' \
#	> $target.build \
#	&& mv $target.build $target

##Convert 
results/%.converted.raw: data/%.vcf.gz
	set -x
	mkdir -p `dirname $target`
	echo "[DEBUGGING] converting coordinates to $target"
	$CROSSMAP vcf \
	$CHAIN \
	$prereq	\
	$TARGET_REFERENCE \
	$target.build \
	&& mv $target.build $target
