< config.mk

results/%.converted.vcf.gz:Q:	results/%.converted.vcf
#	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS sort 
#	bgzip -c $prereq > $target.build \
#	&& tabix -p vcf $target.build \
#	&& mv $target.build $target \
#	&& mv $target.build.tbi $target.tbi #\
#	&& rm $prereq

results/%.converted.vcf: results/%.tmp.header results/%.tmp.body
#	set -x
	mkdir -p `dirname $target`
#	cat $prereq > $target.build \
#	&& mv $target.build $target \
#	&& rm $prereq

results/%.tmp.header: results/%.converted.raw
#	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS view -h $prereq > $target.build \
#	&& mv $target.build $target

##Remove variants with "N" as reference allele; replace MT for "M"; and replace line start (^) with "chr";
results/%.tmp.body: results/%.converted.raw
#	set -x
	mkdir -p `dirname $target`
#	$BCFTOOLS view -H $prereq \
#	| awk ' BEGIN { FS="\t"; OFS="\t"; }
#		$4 !~ /N/ {
#			if ( $1 == "MT" ) $1="M";
#			print "chr"$0
#			} ' \
#	> $target.build \
#	&& mv $target.build $target

##Convert between assemblies
results/%.converted.raw: results/%.pre-processing-check
	set -x
	mkdir -p `dirname $target`
	echo "[DEBUGGING] converting coordinates to $target"
	$CROSSMAP \
		vcf \
		$CHAIN \
		data/$stem.vcf.gz \
		$TARGET_REFERENCE \
		$target.build \
	&& mv $target.build $target

##get contig names and sizes from: input_vcf (from header), col 3 from chain file "^chain" lines; target_reference (fasta headers)
results/%.pre-processing-check:V:
	set -x
	mkdir -p `dirname $target`
	echo "[DEBUGGING] checking contig names"
	$BCFTOOLS view -h data/$stem.vcf.gz | grep "^##contig=<ID=" | cut -d"," -f1 | cut -d"=" -f3 \
		> results/$stem.ivcf_contigs.list \
	&& zgrep "^chain" $CHAIN | cut -d" " -f3 | sort -u \
		> results/$stem.ichain_contigs.list \
	&& grep "^>" $TARGET_REFERENCE | cut -d" " -f1 | tr -d ">" \
		> results/$stem.ofasta_contigs.list \
	&& zgrep "^chain" $CHAIN | cut -d" " -f8 | sort -u \
		> results/$stem.ochain_contigs.list \
	&& echo "The following input contigs won't be translated since chain files does not have the required info \n $(grep -v -x -f results/$stem.ichain_contigs.list results/$stem.ivcf_contigs.list | sed "s#^#\t#")" \
	&& echo "The following output contigs won't be translated since target reference fasta file does not have the required contig name \n $(grep -v -x -f results/$stem.ofasta_contigs.list results/$stem.ochain_contigs.list | sed "s#^#\t#")"
